version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: smartcampus
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    environment:
      DB_URL: postgres://user:password@postgres:5432/smartcampus?sslmode=disable&search_path=users
      JWT_SECRET: your-secret-key
      GRPC_PORT: 50051
    ports:
      - "50051:50051"
    depends_on:
      - postgres

  room-service:
    build: ./room-service
    environment:
      DB_URL: postgres://user:password@postgres:5432/smartcampus?sslmode=disable&search_path=rooms
      GRPC_PORT: 50052
    ports:
      - "50052:50052"
    depends_on:
      - postgres

  booking-service:
    build: ./booking-service
    environment:
      DB_URL: postgres://user:password@postgres:5432/smartcampus?sslmode=disable&search_path=bookings
      GRPC_PORT: 50053
    ports:
      - "50053:50053"
    depends_on:
      - postgres

  notification-service:
    build: ./notification-service
    environment:
      GRPC_PORT: 50054
    ports:
      - "50054:50054"

  api-gateway:
    build: ./api-gateway
    environment:
      HTTP_PORT: 8080
      USER_SERVICE_ADDR: user-service:50051
      ROOM_SERVICE_ADDR: room-service:50052
      BOOKING_SERVICE_ADDR: booking-service:50053
      JWT_SECRET: your-secret-key
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - room-service
      - booking-service

volumes:
  postgres_data: